name: Aspell check
on: [push, workflow_dispatch]

jobs:
  build:
    name: Check with aspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Install aspell
        run: |
          sudo apt-get install aspell aspell-en
      - name: Run spell checker
        uses: actions/checkout@v2.1.0
        id: summary
        run: |
          output = $(inv spellcheck)

  aspell_summary:
    needs: build
    runs-on: ubuntu-latest
    if: success() || failure()
    name: Write output to summary
    steps:
      - name: Print the summary
        run: |
          echo "Summary of the aspell check" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.summary.outputs.content }}" >> $GITHUB_STEP_SUMMARY
